### ISSUE TITLE
rapids-logger headers are separated from stdout outputs in CI logs

### ISSUE THREAD

**Issue by bdice** [rapidsai/gha-tools#94]
CI outputs sometimes don't get stdout/stderr perfectly ordered. I'm seeing outputs like this: https://github.com/rapidsai/cugraph-ops/actions/runs/8068159600/job/22041808067?pr=605#step:7:313

```
RAPIDS logger » [02/27/24 20:03:15]
┌──────────────────┐
|    Print arch    |
└──────────────────┘


RAPIDS logger » [02/27/24 20:03:15]
┌────────────────────────────┐
|    Check python version    |
└────────────────────────────┘


RAPIDS logger » [02/27/24 20:03:15]
┌───────────────────────────────┐
|    Check conda environment    |
└───────────────────────────────┘
```

and then much later in the output, I see

```
x86_64
Python 3.11.8

     active environment : test
    active env location : /opt/conda/envs/test
            shell level : 1
       user config file : /github/home/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 23.11.0
...
```

This could be fixed if we output the `rapids-logger` headers to stdout instead of stderr.

https://github.com/rapidsai/gha-tools/blob/eafb8b262ecfd223f805f8438bb842bb8e1750c3/tools/rapids-logger#L23

**Comment by ajschmidt8** [comment]
I think that change should be fine to make.

From reviewing all the implementations below, I don't think it should cause any issues:

- https://github.com/search?q=org%3Arapidsai+%2Frapids-logger%2F&type=code&p=1

I think we just copy/pasted that convention from the old gpuci_logger
